### ISSUE TITLE
nvcc fatal : Unsupported gpu architecture 'compute_60'

### ISSUE THREAD

**Issue by ruiwang2uber** [openai/blocksparse#21]
try `make compile`:  it went smoothly until i hit

nvcc fatal   : Unsupported gpu architecture 'compute_60'
Makefile:105: recipe for target 'build/batch_norm_op_gpu.cu.o' failed
make: *** [build/batch_norm_op_gpu.cu.o] Error 1

Could you please help?

**Comment by ThomasHagebols** [comment]
Could you give some more details? What configuration are you running? Which versions of python, tensorflow, cuda, cudnn and nccl? Which OS are you running? Which compiler?

**Comment by ruiwang2uber** [comment]
Thanks, @ThomasHagebols 
OS: ubuntu 16.04 LTS
Python: Python 3.6.8
Tensorflow: 1.13.1
cuda:
cudnn:
nccl
