### ISSUE TITLE
how to use the BlocksparseMatMul

### ISSUE THREAD

**Issue by VivaLaTian** [openai/blocksparse#25]
When I run the /example/simple.py, I get two different answer between the old and new blocksparse.The dimension of the result has been changed.
y=bsmm(x,w)
x's shape = (64,4096)
and w= (4096,4096)
the old blocksparse get y's shape =(64,4096)
but now it is (4096,4096)
So I wonder know how to use the BlocksparseMatMul after the update of last month.

**Comment by scott-gray** [comment]
Maybe send me more complete code sample that can be run.   One thing to note is that we've switched to 100% V100 compute here and I don't spend much time testing older cards anymore.  I've even removed some old code pathways.  Perhaps you were using one.  In which case you should be able to continue using an old branch or patch something together on your own combining old and new.

**Comment by VivaLaTian** [comment]
an example as below.
--------------------------------------------------------------
from blocksparse.matmul import BlocksparseMatMul
import tensorflow as tf
import numpy as np

hidden_size = 4096
block_size = 32
minibatch_size = 64

# Create a (random) sparsity pattern
sparsity = np.ones((hidden_size//block_size,hidden_size//block_size))

# Initialize the sparse matrix multiplication object
bsmm = BlocksparseMatMul(sparsity, block_size=block_size)

# Input to graph
x = tf.placeholder(tf.float32, shape=[None, hidden_size])

# Initialize block-sparse weights
w = tf.ones(bsmm.w_shape, dtype=tf.float32)

# Block-sparse matrix multiplication
y = bsmm(x, w)

# Run
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
result = sess.run([y], feed_dict = {x: np.ones((minibatch_size,hidden_size), dtype='float32')})
print(result)
print(result[0].shape)

when I run the above code, the answer is [4096,4096] and each value is 64.
![image](https://user-images.githubusercontent.com/26855340/57698594-8f1a3500-7688-11e9-9f6d-eba0f9be47ca.png)

but I think it should be[64,4096] and each value is 4096.
So I am really confused about how to use the BlocksparseMatMul.

**Comment by scott-gray** [comment]
I changed the default feature_axis from 1 to 0.  Can you check if making that explicit fixes things for you?

**Comment by VivaLaTian** [comment]
thanks! it works.
