### ISSUE TITLE
The position encoding of enwik8.py is not right.

### ISSUE THREAD

**Issue by AranKomat** [openai/blocksparse#34]
According to the paper,

> For text and audio, we used two-dimensional attention embeddings, where dattn = 2 and the index corresponds to each position’s row and column index in a matrix of width equal to the stride.

This isn't reflected in 'p_emb' of enwik8.py.

**Comment by scott-gray** [comment]
That code is just an engineering sample with simpler embeddings.  It was not used to train the model in the paper (but has many of the elements put together in a working example).

**Comment by AranKomat** [comment]
OK. I just wanted to make it clear. Thanks for your response.
