### ISSUE TITLE
where is the implementation of Factorized self-attention?

### ISSUE THREAD

**Issue by world2vec** [openai/blocksparse#37]
Hi,
Good job.
I am looking for the code about the implementation of factorized self-attention in the enwiki8 example, could you point me which lines of code was related(I did not found, looks it only mask out the blocks in future)?

**Comment by scott-gray** [comment]
That code is more of an engineering sample (but still pretty useful as a working starting point).  Look here for the attention patterns used in the paper:

https://github.com/openai/sparse_attention
