### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jiaboli007** [openai/blocksparse#6]
I installed blocksparse by following the instructions, and tested with the example. I got the following error:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from blocksparse.matmul import BlocksparseMatMul
  File "/usr/local/lib/python2.7/dist-packages/blocksparse/matmul.py", line 13, in <module>
    import blocksparse.ewops as ew
  File "/usr/local/lib/python2.7/dist-packages/blocksparse/ewops.py", line 162
    def fused_lstm_gates(c, *args, name=None):
                                      ^
SyntaxError: invalid syntax

I am working on AWS p2 instance with Ubuntu 16, tensorflow 1.4.1, python 2.7, cuda-8.0, cudnn-6.0. The installation does not show any problem, but I have to put __init__.py in the blocksparse package folder, other wise the import blocksparse does not work. 

I also tried many other ways, including python 3, and non was working.

**Comment by scott-gray** [comment]
Sorry the init file somehow got left out of initial release.  That's fixed.
