### ISSUE TITLE
Getting undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

### ISSUE THREAD

**Issue by dchichkov** [openai/blocksparse#7]
With TF 1.5rc0, CUDA 9.1 on commit 8095147a9c02254cb6  the library builds/installs successfully (with 'make compile', pip install dist/*.whl), but I'm getting:

```

~/n/blocksparse/examples (master) $ python simple.py 
Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    from blocksparse.matmul import BlocksparseMatMul
  File "~/.local/lib/python2.7/site-packages/blocksparse/matmul.py", line 13, in <module>
    import blocksparse.ewops as ew
  File "/home/dchichkov/.local/lib/python2.7/site-packages/blocksparse/ewops.py", line 17, in <module>
    _op_module = tf.load_op_library(os.path.join(data_files_path, 'blocksparse_ops.so'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: 
/~/.local/lib/python2.7/site-packages/blocksparse/blocksparse_ops.so: undefined symbol: 
_ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

```

Oh, and python is spitting out syntax error in the def fused_lstm_gates(c, *args, name=None) see #8, and I guess replacing the order of *args and the default variable would be an incorrect fix.

**Comment by dchichkov** [comment]
Here's the issue that was breaking it (from https://github.com/tensorflow/models/blob/master/tutorials/embedding/README.md):  

The flag -D_GLIBCXX_USE_CXX11_ABI=0 is included to support newer versions of gcc. However, if you compiled TensorFlow from source using gcc 5 or later, you may need to exclude the flag. Specifically, if you get an error similar to the following: word2vec_ops.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_ then you likely need to exclude the flag.

**Comment by scott-gray** [comment]
Ok, the makefile is updated to detect the correct value of _GLIBCXX_USE_CXX11_ABI to use.

**Comment by mehari** [comment]
Pleas could any one help me resolve this problem 
" lib_handle = py_tf.TF_LoadLibrary(library_filename)", "NotFoundError: C:\Users\research\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.so not found"

**Comment by Fazankabir** [comment]
@mehari i am also having the similar error

**lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\kabirfaz\Documents\MyData\02_MyProjects\05_P600_Handsigns\venv\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\_tensor_forest_ops.so not found**

Please help if you have found the solution
